### ISSUE TITLE
Build an automated YAML header builder

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/KuskoHarvEst#63]
Based on the contents of the meta data file and the choice of whether the document is a sensitivity analysis or an in-season report, we need to build a YAML header with the correct options. I.e., the creation of this must be automated:

```yaml
---
title: "Kuskokwim River In-season Harvest/Effort Sensitivity Analysis"
draft-watermark: false
output: 
  pdf_document:
    template: "C:/Users/bstaton/Desktop/Staton/5_qes/01-projects/2021_KuskoHarvEst_BSFA/analyses/KuskoHarvEst/inst/early-template.tex"
editor_options: 
  chunk_output_type: console
opener-label: "6/12/2018 Subsistence Harvest Opportunity"
opener-start: "6/12/2018 10:00 AM"
opener-end: "6/12/2018 10:00 PM"
area: "Tuntutuliak -- Akiak"
special-action-url: http://example.com
news-release-url: http://example.com
contact: "Ben Staton (bstaton.qes@gmail.com)"
doc-label: "Sensitivity Analyses"
---
```
